### ISSUE TITLE
'DataGenerator' object has no attribute 'only_close_tumor'

### ISSUE THREAD

**Issue by HilbertMaximov** [TheoEst/joint_registration_tumor_segmentation#5]
![image](https://user-images.githubusercontent.com/59821328/174976260-a73d6895-0d3f-429e-956b-1e8410827567.png)
![image](https://user-images.githubusercontent.com/59821328/174976377-36d5f53f-0d93-43f7-a970-0fbfabe1f3fa.png)
![image](https://user-images.githubusercontent.com/59821328/174976416-fc5c5661-1634-4648-9401-a833a74155e2.png)
How should I change it?

**Comment by TheoEst** [comment]
Fix in 2cefdeb1e00c8516bb1382697dd11ccb73cdbdb1
